### ISSUE TITLE
Create resources page

### ISSUE THREAD

**Issue by thewells1024** [WhiteHatCP/thewhitehat.club#13]
Create a page with resources such as links to Privacy Badger, HTTPS Everywhere, VPN suggestions, and other resources as a reference that members can both use and refer others to.

**Comment by xzinkus** [comment]
+1, as well as links to papers, tutorials, etc. Thanks!

**Comment by jon77p** [comment]
Resolved in redesigned website (Commit 958e719617a1e21c18fad590b134fc0d1f7c2589)
