### ISSUE TITLE
Create Travis-CI integration

### ISSUE THREAD

**Issue by thewells1024** [WhiteHatCP/thewhitehat.club#16]
pull config from seclab-timecard

**Comment by slashnick** [comment]
Check out `.git/hooks/post-receive` for the timecard

**Comment by matthewlewis112** [comment]
Also, if you are using pytester, you shouldn't have an __inti__.py in your website util folder.

**Comment by sjfoz1019** [comment]
Implemented in 3549b78. Thanks Matthew!
