### ISSUE TITLE
Extra Resources Resources

### ISSUE THREAD

**Issue by thewells1024** [WhiteHatCP/thewhitehat.club#19]
* [LLDB](https://lldb.llvm.org/): A reimplimentation of GDB targeted at LLVM based systems, useful for debugging on Mac (also has a nicer UI than GDB)

* [MicroCorruption](https://lldb.llvm.org/): Embedded System CTF, good for learning the basics of ASM

**Comment by jon77p** [comment]
Resolved in commit c200c25
