### ISSUE TITLE
Additional Hacking Books

### ISSUE THREAD

**Issue by sig1nt** [WhiteHatCP/thewhitehat.club#20]
**Is your feature request related to a problem? Please describe.**
You don't have the thing I want

**Describe the solution you'd like**
Add the thing

**Describe alternatives you've considered**
Not adding the thing

**Additional context**
We should have additional books, such as the "The Tangled Web" and "The Web Application Hacker's Handbook"

**Comment by jon77p** [comment]
Resolved in commit 960a048
