### ISSUE TITLE
Aesthetic issue in officer page

### ISSUE THREAD

**Issue by sig1nt** [WhiteHatCP/thewhitehat.club#21]
**Describe the bug**
See screenshot

**Website Page URL**
https://thewhitehat.club/officers

**To Reproduce**
1. Go to https://thewhitehat.club/officers
2. Notice the placement of the bottom officer pictures

**Expected behavior**
Officer pictures should remain above the footer bar despite screen size

**Screenshots**
<img width="1440" alt="screen shot 2019-02-15 at 2 16 38 pm" src="https://user-images.githubusercontent.com/8923630/52887397-67204180-312c-11e9-9edb-ff453d00c912.png">

**Desktop (please complete the following information):**
 - Hardware: Macbook Pro 2016, 15'
 - OS: MacOS 10.13.6
 - Browser Firefox 65.0

**Comment by jon77p** [comment]
The size it's breaking at is **936x615** for the _officer-container_ div, TODO: fix presumably vertical scaling of internal contents

**Comment by slashnick** [comment]
Unsubscribe

**Comment by sjfoz1019** [comment]
Added scrolling to accommodate a larger number of officers in #a7cbde0 so this bug is no longer noticable, but probably still exists.

**Comment by jon77p** [comment]
Closing due to partial fix
