### ISSUE TITLE
Switch to Angular

### ISSUE THREAD

**Issue by thewells1024** [WhiteHatCP/thewhitehat.club#23]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Use Angular as a rendering framework, this will allow you to make `app.py` much simpler, and will allow you to take advantage of the API that you are developing

**Describe alternatives you've considered**
Stay with how things are.
React 🤮

**Additional context**
Angular Documentation: https://angular.io/docs
Angular Tutorial: https://angular.io/tutorial
This is somewhat related to https://github.com/WhiteHatCP/thewhitehat.club/issues/22

**Comment by jon77p** [comment]
This suggestion has been implemented with considerations described in the [Design Considerations Wiki Page](https://github.com/WhiteHatCP/thewhitehat.club/wiki/Implementation-Design-Considerations). As such, we will be staying with Flask, but working off of the API routes that have already been made generic in commit 87045e9, which allows for generic page rendering to occur and utilize the data from the API endpoints.

Closed by commit 4d4f55f.
