### ISSUE TITLE
Remove service workers that are trying to save things on people’s computer

### ISSUE THREAD

**Issue by thewells1024** [WhiteHatCP/thewhitehat.club#27]
**Describe the bug**
Websites should never try to save things to a person’s computer without explicit permission

**Additional context**
Trying to cache content on a web page is not a good idea

**Comment by slashnick** [comment]
(Unsolicited advice y’all can ignore)

Oh wow this code is weird. Your browser is actually really good at caching static files served by nginx.

**Comment by thewells1024** [comment]
@nickfrostatx That was my point, the browser will do a lot of caching on it's own, so there isn't a good reason for a website to cache things on it's own, and never without explicit permission. Browsers at least give some control.
