### ISSUE TITLE
Add VMware Slides to Resources Page

### ISSUE THREAD

**Issue by jon77p** [WhiteHatCP/thewhitehat.club#28]
**Is your feature request related to a problem? Please describe.**
Nope! This is a request for an addition to the resource page made by Kylan, posted here by me.

**Describe the solution you'd like**
We would like to have the slides from the talks with VMware on the resources page of the site.

**Describe alternatives you've considered**
N/A

**Additional context**
Reach out to me for the slides, also I'll help you get this underway too.

**Comment by sjfoz1019** [comment]
Closed in 45b3dd7
