### ISSUE TITLE
Add Type Hinting

### ISSUE THREAD

**Issue by thewells1024** [WhiteHatCP/thewhitehat.club#34]
**Is your suggested optimization related to a problem or bug? Please describe.**
Python3 allows programmers to type hint, increasing the effectiveness of tools such as IDEs

**Describe the solution you'd like**
add [type hinting](https://docs.python.org/3/library/typing.html) to the files (especially the `website_utils` module). This should require no system changes as type hinting is transparent at runtime

**Describe alternatives you've considered**
* Not adding Type Hinting
  * Requires developer to read entire code base to make any changes, and limits tool effectiveness
* Adding Type information in doc strings
  * While allowing functions and methods to be more opaque, still limits tool effectiveness

**Comment by jon77p** [comment]
Reassigned to current webmaster

**Comment by sjfoz1019** [comment]
Closed by 2c62a0636c233bd60f472c94e49499894d2e2bd8
