### ISSUE TITLE
CSS fixes: Mobile

### ISSUE THREAD

**Issue by xzinkus** [WhiteHatCP/thewhitehat.club#4]
Please review, test, and fix for Mobile Safari, iOS Chrome, and Android Chrome (if they differ)

**Comment by DeltaHeavy** [comment]
!important

**Comment by slashnick** [comment]
Changing the viewport size in c71a798 seems to have improved the look of the site on mobile.  There are still problems, so this issue remains open.

**Comment by xzinkus** [comment]
@nickfrostatx please describe the changes you had in mind in the comments here

**Comment by slashnick** [comment]
Take a look at the white line above the "Our mission is" paragraph. It's two dark grey boxes right next to each other on a white background, and the white shows on mobile. One possible solution would be to have the two boxes slightly overlap.

![image](https://cloud.githubusercontent.com/assets/839071/25035382/33051ebc-20a2-11e7-8f90-353a62c1a1e8.png)

**Comment by xzinkus** [comment]
Not sure if this is for this issue or another one, but MobileSafari on my phone won't show the calendar?
